/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppOptionsPage {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppOptionsPageElement extends Components.AppOptionsPage, HTMLStencilElement {
    }
    var HTMLAppOptionsPageElement: {
        prototype: HTMLAppOptionsPageElement;
        new (): HTMLAppOptionsPageElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-options-page": HTMLAppOptionsPageElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppOptionsPage {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-options-page": AppOptionsPage;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-options-page": LocalJSX.AppOptionsPage & JSXBase.HTMLAttributes<HTMLAppOptionsPageElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
